//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvcStajOdevi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        public int ID { get; set; }
        public string Isim { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Kabul { get; set; }
        public string Memnun { get; set; }
        public string Konu { get; set; }
        public string Beklenti { get; set; }
        public string Maas { get; set; }
        public string Calisan { get; set; }
    }
}
